ExData <- read.table("household_power_consumption.txt",sep =";",na.strings="?",header=TRUE)
ExData$Time <- (strptime(paste(as.character(ExData$Date),as.character(ExData$Time)),"%d/%m/%Y %H:%M:%S"))
ExData$Date <- as.Date(as.character(ExData$Date), "%d/%m/%Y")
ExData2 <- subset(ExData,(ExData$Date>=as.Date("2007-02-01"))&(ExData$Date<=as.Date("2007-02-02")))
png("plot1.png", width=480, height=480)
par(mfrow=c(1,1))
hist(ExData2$Global_active_power,main="Glabal Active Power",xlab="Global Active Power(kilowatts)",col="#FF0000",xlim=c(0,6))
#dev.copy(png,file="plot1.png",width = 480, height = 480)
dev.off()
